### ISSUE TITLE
RTSP stream conversion

### ISSUE THREAD

**Issue by km147** [bgrins/videoconverter.js#37]
Hi,

I was wondering if it was possible to use this to convert and rtsp stream? The following ffmpeg arguments give me a 'Protocol not found' error.

arguments: [ 
     "-i", input, "-vcodec", "copy", "-f", "mp4", "-movflags", "frag_keyframe+empty_moov", "-r", "25",
    "-reset_timestamps", "1", "-vsync", "1","-flags", "global_header", "-bsf:v", "dump_extra", "-y", "-"  
 ]

Is there something i'm missing?

**Comment by shawndowney** [comment]
+This compiled version (from what I can work out) does not include any bit stream filters. Command --list-bsfs returns no filters. You cannot manage streams with videoconverter.js

**Comment by vijaykumarchettiar** [comment]
hello
i pulled your branch and compile it with options of --enable-protocols --enable-network in order to input the rtmp or rtsp url and output as webm or mp4 files.

however the compiled with error as below

'/home/ubuntu/emi/emsdk-portable/clang/e1.38.28_64bit/binaryen/bin/asm2wasm ../ffmpeg.temp.asm.js --total-memory=33554432 --trap-mode=allow -O3 --mem-init=../ffmpeg.js.mem --mem-base=1024 --wasm-only -o ../ffmpeg.wasm --mvp-features' failed (-9)

did you try these options?

the ffmpeg is 2014 build as it's fetched in the fetch_sources.sh
